# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# smdk4x12. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that smdk4x12 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

LOCAL_PATH := device/hardkernel/odroidu2

include $(LOCAL_PATH)/BoardConfig.mk

ifeq ($(BOARD_USES_EMMC),true)
DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay
else
DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay_sd
endif

ifeq ($(BOARD_USES_HGL),true)
PRODUCT_COPY_FILES += \
	device/samsung/smdk4x12/conf/egl.cfg:system/lib/egl/egl.cfg \
	device/samsung/exynos4/lib/mali_ump/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
	device/samsung/exynos4/lib/mali_ump/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
	device/samsung/exynos4/lib/mali_ump/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
	device/samsung/exynos4/lib/mali_ump/libMali.so:system/lib/libMali.so \
	device/samsung/exynos4/lib/mali_ump/libMali.so:obj/lib/libMali.so \
	device/samsung/exynos4/lib/mali_ump/libUMP.so:system/lib/libUMP.so \
	device/samsung/exynos4/lib/mali_ump/libUMP.so:obj/lib/libUMP.so \
	device/samsung/exynos4/lib/mali_ump/libion.so:system/lib/libion.so \
	device/samsung/exynos4/lib/mali_ump/libion.so:obj/lib/libion.so
endif

ifeq ($(BOARD_USES_EMMC),true)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/vold_emmc.fstab:system/etc/vold.fstab
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/vold_sd.fstab:system/etc/vold.fstab
endif

# Init files

ifeq ($(BOARD_WLAN_DEVICE), rt5370sta)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/init.odroidu2.rc:root/init.odroidu2.rc 
else ifeq ($(BOARD_WLAN_DEVICE), rtl8191su)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/init.odroidu2_realtek.rc:root/init.odroidu2.rc 
endif
	
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/init.odroidu2.usb.rc:root/init.odroidu2.usb.rc 

# WIFI TOOL COPY
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/etc/iwconfig:system/bin/iwconfig \
	device/hardkernel/proprietary/etc/iwlist:system/bin/iwlist

#
# USB Ethernet Module
#
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/smsc95xx_u.ko:system/lib/modules/smsc95xx.ko

#-------------------------------------------------------------------------------------
#
# WIFI firmware
#
#-------------------------------------------------------------------------------------
ifeq ($(BOARD_WLAN_DEVICE),rt5370sta)

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/rt5370sta.ko:system/lib/modules/rt5370sta.ko \
	device/hardkernel/proprietary/bin/rt5370sta.cal:system/etc/firmware/rt5370sta.cal 

PRODUCT_PROPERTY_OVERRIDES += \
	wifi.interface=ra0 \
	wifi.supplicant_scan_interval=15

else ifeq ($(BOARD_WLAN_DEVICE), rtl8191su)
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/rtl8191su.ko:system/lib/modules/rtl8191su.ko \

PRODUCT_PROPERTY_OVERRIDES += \
	wifi.interface=wlan0 \
	wifi.supplicant_scan_interval=15
endif

# For V4L2
ifeq ($(BOARD_USE_V4L2), true)
ifeq ($(BOARD_USE_V4L2_ION), true)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/ueventd.odroidu2.v4l2ion.rc:root/ueventd.odroidu2.rc
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/ueventd.odroidu2.v4l2.rc:root/ueventd.odroidu2.rc
endif
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/conf/ueventd.odroidu2.rc:root/ueventd.odroidu2.rc
endif

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/bin/odroid-ts.idc:system/usr/idc/odroidu-ts.idc \
	device/hardkernel/proprietary/bin/odroid-ts.kl:system/usr/keylayout/odroidu-ts.kl \
	device/hardkernel/proprietary/bin/odroid-ts.kcm:system/usr/keylayout/odroidu-ts.kcm \
	device/hardkernel/proprietary/bin/odroid-keypad.kl:system/usr/keylayout/odroid-keypad.kl \
	device/hardkernel/proprietary/bin/odroid-keypad.kcm:system/usr/keychars/odroid-keypad.kcm

# Filesystem management tools
PRODUCT_PACKAGES += \
	make_ext4fs \
	setup_fs

# audio
PRODUCT_PACKAGES += \
	audio_policy.$(TARGET_PRODUCT) \
	audio.primary.$(TARGET_PRODUCT) \
	audio.a2dp.default \
	libaudioutils

# ULP Audio
ifeq ($(USE_ULP_AUDIO),true)
PRODUCT_PACKAGES += \
	libaudiohw \
	MusicULP \
	libsa_jni
endif

# ALP Audio
ifeq ($(BOARD_USE_ALP_AUDIO),true)
PRODUCT_PACKAGES += \
	libOMX.SEC.MP3.Decoder
endif

# Camera
PRODUCT_PACKAGES += \
	camera.$(TARGET_PRODUCT)

# SEC_Camera
ifeq ($(USE_SEC_CAMERA),true)
PRODUCT_PACKAGES += \
	SEC_Camera
endif

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libstagefrighthw \
	com.android.future.usb.accessory

# Video Editor
PRODUCT_PACKAGES += \
	VideoEditorGoogle

# Misc other modules
PRODUCT_PACKAGES += \
	lights.$(TARGET_PRODUCT) \
	hwcomposer.$(TARGET_BOARD_PLATFORM) \
	gralloc.$(TARGET_PRODUCT)

# Widevine DRM
PRODUCT_PACKAGES += com.google.widevine.software.drm.xml \
	com.google.widevine.software.drm \
	WidevineSamplePlayer \
	test-libwvm \
	test-wvdrmplugin \
	test-wvplayer_L1 \
	libdrmwvmplugin \
	libwvm \
	libWVStreamControlAPI_L1 \
	libwvdrm_L1

# OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidu2/media_profiles.xml:system/etc/media_profiles.xml

# OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libSEC_OMX_Resourcemanager \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# hwconvertor modules
PRODUCT_PACKAGES += \
	libhwconverter \

# gps
PRODUCT_PACKAGES += \
	gps.$(TARGET_PRODUCT)

# MFC firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin

# FIMC-IS firmware
PRODUCT_COPY_FILES += \
	device/samsung/exynos4/firmware/fimc_is_fw.bin:system/vendor/firmware/fimc_is_fw.bin \
	device/samsung/exynos4/firmware/setfile.bin:system/vendor/firmware/setfile.bin \
	device/samsung/exynos4/firmware/setfile_S5K3H7.bin:system/vendor/firmware/setfile_S5K3H7.bin

#-------------------------------------------------------------------------------------
#
# framework permission file
#
#-------------------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
	frameworks/base/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	frameworks/base/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml \
	frameworks/base/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

PRODUCT_COPY_FILES += \
	device/samsung/exynos4/libgralloc_ump/gralloc.odroidu.so:system/lib/hw/gralloc.odroidu2.so
	
# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072

PRODUCT_PROPERTY_OVERRIDES += \
	hwui.render_dirty_regions=false

# Widevine DRM
PRODUCT_PROPERTY_OVERRIDES += \
	drm.service.enabled=true

# Set default USB interface
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
	persist.sys.usb.config=mass_storage

ifeq ($(BOARD_USES_HIGH_RESOLUTION_LCD),true)
PRODUCT_CHARACTERISTICS := tablet

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml

$(call inherit-product, frameworks/base/build/tablet-dalvik-heap.mk)

else
PRODUCT_CHARACTERISTICS := phone

PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml

$(call inherit-product, frameworks/base/build/phone-hdpi-512-dalvik-heap.mk)

PRODUCT_PROPERTY_OVERRIDES += \
	ro.sf.lcd_density=160

PRODUCT_AAPT_CONFIG := normal hdpi
endif

USE_PIXTREE_STAGEFRIGHT := false

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/apk/odroidhwoc.apk:system/app/odroidhwoc.apk \
	device/hardkernel/proprietary/apk/ODROID-4.0-v1.9.apk:system/app/ODROID.apk \
	device/hardkernel/proprietary/apk/Terminal-v1.3.apk:system/app/Terminal-v1.3.apk \
	device/hardkernel/proprietary/apk/FileExplorer-v1.0.apk:system/app/FileExplorer-v1.0.apk \
	device/hardkernel/proprietary/lib/libterminal.so:system/lib/libterminal.so \
	device/hardkernel/proprietary/apk/com.slideme.sam.manager-4.5.apk:system/app/slideme-4.5.apk

PRODUCT_COPY_FILES += \
	device/hardkernel/proprietary/apk/DicePlayer_2_0_18.apk:system/app/DicePlayer_2_0_18.apk \
	device/hardkernel/proprietary/lib/libSoundTouch.so:system/lib/libSoundTouch.so \
	device/hardkernel/proprietary/lib/libdice_ics.so:system/lib/libdice_ics.so \
	device/hardkernel/proprietary/lib/libdice_jb.so:system/lib/libdice_jb.so \
	device/hardkernel/proprietary/lib/libdice_loadlibrary.so:system/lib/libdice_loadlibrary.so \
	device/hardkernel/proprietary/lib/libdice_software.so:system/lib/libdice_software.so \
	device/hardkernel/proprietary/lib/libdice_software_ics.so:system/lib/libdice_software_ics.so \
	device/hardkernel/proprietary/lib/libdice_software_jb.so:system/lib/libdice_software_jb.so \
	device/hardkernel/proprietary/lib/libffmpeg_dice.so:system/lib/libffmpeg_dice.so
